[package]
name = "ystd"
version = "0.1.0"
edition = "2024"

[dependencies]
camino = "1.1.10"
color-eyre = "0.6.5"
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["fs"] }
tracing = "0.1.41"

[lints]
workspace = true
