[package]
name = "ystd"
description = "An opinionated and batteries included `std` mirror for convenient, correct code and pleasant error messages"
documentation = "https://docs.rs/ystd"
homepage = "https://lib.rs/ystd"
repository = "https://github.com/ActuallyHappening/YMap/tree/yit"
license = "MIT"
version = "0.0.3"
edition = "2024"
publish = true

[dependencies]
camino = "1.1.10"
color-eyre = "0.6.5"
extension-traits = { version = "2.0.0" }
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["rt"] }
tracing = "0.1.41"

[lints]
workspace = true

[features]
