[workspace]
members = [
    "app",
    "cas",
    "db",
    "db/layers",
    "generic-error",
    "latex",
    "mathquill/*",
    "testing",
    "thing",
    "thing/macros",
    "utils",
    "dioxus",
    "dioxus",
    "leptos-rsx",
]
resolver = "3"


[workspace.dependencies]
utils = { path = "./utils" }
mathquill-leptos = { path = "./mathquill/leptos" }
cas = { path = "./cas" }
latex-parser = { path = "./latex" }
surrealdb-layers = { path = "./db/layers" }
db = { path = "./db" }
thing = { path = "./thing" }
thing-macros = { path = "./thing/macros" }
generic-err = { path = "./generic-error" }
leptos-rsx = { path = "./leptos-rsx" }

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
