[package]
name = "ymap"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[workspace.dependencies]
ymap-sets = { path = "crates/ymap-sets" }
ymap-functions = { path = "crates/ymap-functions"}


[dependencies]
