[workspace]
resolver = "3"
members = ["app", "cas", "db", "latex", "mathquill/*", "things", "utils"]


[workspace.dependencies]
utils = { path = "./utils" }
mathquill-leptos = { path = "./mathquill/leptos" }
cas = { path = "./cas" }
