[package]
name = "ymap"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.lints.rust]
rust-2018-idioms = "deny"

[workspace.dependencies]
ymap-sets = { path = "crates/ymap-sets" }
ymap-functions = { path = "crates/ymap-functions" }


[dependencies]
bevy = "0.14.2"
