[workspace]
members = ["crates/*", "crates/yscribble/bevy_*"]
exclude = ["crates/testing-winit"]
resolver = "2"

[workspace.dependencies]
surrealdb = "1.5.3"

[workspace.dependencies.yutils]
path = "crates/yutils"

[workspace.dependencies.bevy_yscribble_3d]
path = "crates/yscribble/bevy_yscribble_3d"
features = ["bevy_replicon_replicated"]

[workspace.dependencies.ysurreal]
path = "crates/ysurreal"

[workspace.lints.clippy]
type_complexity = "allow"

[workspace.metadata.scripts]
dev-install = "cargo install nu cargo-run-script apple-clis cargo-all-features cargo-bundle"

## For correct egui version
[workspace.dependencies.bevy_editor_pls]
# version = "0.8.1"
git = "https://github.com/ActuallyHappening/bevy_editor_pls.git"
branch = "update-gizmos"

# ## For Apple pencil double tap support
# [patch.crates-io.winit]
# # version = "0.29"

# # git = "https://github.com/ActuallyHappening/winit.git"
# # branch = "remove-noisy-logs"

# path = "../winit"
# # branch = "testing-pen-taps"

# [workspace.dependencies.bevy]
# version = "0.13.2"
# features = ["serialize"]
# # git = "https://github.com/ActuallyHappening/bevy.git"
# # branch = "add-ansi-log-option"

## When not using apple pencil double tap support
[workspace.dependencies.bevy]
version = "0.13.2"
features = ["serialize"]


## For `Debug` impl on `ParentSync`
[patch.crates-io.bevy_replicon]
# version = "0.26.3"
# git = "https://github.com/ActuallyHappening/bevy_replicon.git"
# branch = "debug-parent-sync"
git = "https://github.com/projectharmonia/bevy_replicon.git"
branch = "master"

########## YMAP ##########

[package]
name = "ymap"
version = "0.1.0"
edition = "2021"
description = "test-ios app"
default-run = "ymap"
publish = false

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
## If enabled, will not link in production secrets
## ENABLE THIS FOR PRODUCTION BUILDS
production = []
default = ["debug"]
ios = []
## Enabled bevy_yscribble_3d/debug
debug = ["bevy_yscribble_3d/debug"]

[package.metadata.xcode-build-rs.ios]
## What features to enable for `io` builds, see `xcode-build-rs` for more information
features = ["ios"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ysurreal.workspace = true
bevy.workspace = true
bevy_editor_pls.workspace = true
bevy_yscribble_3d.workspace = true
bevy_cosmic_edit = { version = "0.20.0", features = ["multicam"] }
bevy_egui = "0.27.1"
derive_more = "0.99.17"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["fmt"] }
bevy_replicon = "0.26.3"
bevy_replicon_renet = "0.3.0"
clap = { version = "4.5.7", features = ["derive", "env"] }
color-eyre = "0.6.3"
serde = { version = "1.0.203", features = ["derive"] }
extension-traits = "1.0.1"
tracing-error = "0.2.0"
tokio = { version = "1.38.0", features = ["full"] }
openssh = { version = "0.10.4", features = ["native-mux", "openssh-mux-client"] }
camino = "1.1.7"
bossy = "0.2.1"

[package.metadata.bundle]
identifier = "com.ymap.test-ios69"
resources = ["assets"]

[package.metadata.scripts]
open-xcode = "open xcode/*.xcodeproj"
# open-app = "open xcode/build/Debug-iphoneos/YMap.app"

[package.metadata.cargo-all-features]
denylist = ["production"]

[lints]
workspace = true

[[bin]]
name = "db"