[package]
name = "ymap"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
members = ["crates/*", "xtask"]
resolver = "2"

[workspace.package]
repository = "https://github.com/ActuallyHappening/YMap"

[workspace.lints.rust]
rust-2018-idioms = "deny"

[workspace.dependencies]
ymap-sets = { path = "crates/ymap-sets" }
db-credentials = { path = "crates/db-credentials" }


[dependencies]
bevy_egui = "0.31"                                                                                     # Old to keep up with bevy_editor_pls
egui = "0.29"                                                                                          # Old to keep up with bevy_editor_pls
bevy = "0.15.0"
bevy_editor_pls = { version = "0.11.0", git = "https://github.com/ActuallyHappening/bevy_editor_pls" }

[patch.crates-io]
# for bevy_editor_pls dep
transform-gizmo-bevy = { git = "https://github.com/ActuallyHappening/transform-gizmo" }

[dependencies.bevy_cosmic_edit]
version = "0.26.0"
# git = "https://github.com/ActuallyHappening/bevy_cosmic_edit"
path = "../bevy_cosmic_edit"
