[package]
name = "ymap"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
members = ["crates/*"]
repository = "https://github.com/ActuallyHappening/YMap"
resolver = "2"

[workspace.lints.rust]
rust-2018-idioms = "deny"

[workspace.dependencies]
ymap-sets = { path = "crates/ymap-sets" }


[dependencies]
bevy = { version = "0.14.2", features = ["dynamic_linking"] }
bevy_editor_pls = "0.10.0"
bevy_editor_pls_core = "0.10.0"
bevy_egui = "0.29"                                            # Old to keep up with bevy_editor_pls
egui = "0.28"                                                 # Old to keep up with bevy_editor_pls

[dependencies.bevy_cosmic_edit]
version = "0.25.0"
features = ["multicam"]
path = "bevy_cosmic_edit"
