[package]
name = "ymap"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.lints.rust]
rust-2018-idioms = "deny"

[workspace.dependencies]
ymap-sets = { path = "crates/ymap-sets" }


[dependencies]
bevy = { version = "0.14.2", features = ["dynamic_linking"] }
bevy_cosmic_edit = { version = "0.25.0", features = ["multicam"] }
bevy_editor_pls = "0.10.0"
