[workspace]
members = [
    "app",
    "cas",
    "db",
    "db/layers",
    "generic-error",
    "latex",
    "mathquill/*",
    "thing",
    "thing/macros",
    "utils",
]
resolver = "3"


[workspace.dependencies]
utils = { path = "./utils" }
mathquill-leptos = { path = "./mathquill/leptos" }
cas = { path = "./cas" }
latex-parser = { path = "./latex" }
surrealdb-layers = { path = "./db/layers" }
db = { path = "./db" }
thing = { path = "./thing" }
thing-macros = { path = "./thing/macros" }
