[package]
name = "xserver"
edition = "2024"
version = "0.1.0"

[features]
prod = []

[dependencies]
env = { workspace = true, features = [
    "db",
    "db-root-creds",
], default-features = false }
utils = { workspace = true, features = ["cli-support"] }
filesize = "0.2.0"
size = "0.5.0"

[dependencies.cargo-leptos]
# path = "/home/ah/Desktop/cargo-leptos"
# version = "0.2.27"
git = "https://github.com/ActuallyHappening/cargo-leptos.git"
# branch = "library-usage3"
branch = "tracing-upgrade"
