[package]
name = "xserver"
edition = "2024"
version = "0.1.0"

[features]

[dependencies]
utils = { workspace = true, features = ["cli"], default-features = false }
filesize = "0.2.0"
size = "0.5.0"

[dependencies.cargo-leptos]
# path = "/home/ah/Desktop/cargo-leptos"
# version = "0.2.27"
# git = "https://github.com/ActuallyHappening/cargo-leptos.git"
# branch = "library-usage3"
# branch = "tracing-upgrade"
rev = "cebe070e1a12de11563ae8c1f76ecf2313bd539a"
git = "https://github.com/leptos-rs/cargo-leptos.git"
