[package]
name = "latex-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8.0.0"
nom-language = "0.1.0"
num = { version = "0.4.3", features = ["num-bigint"] }
thiserror = "2.0.12"
tracing = "0.1.41"
