[package]
edition = "2024"
name = "app"
version = "0.1.0"

[features]

[dependencies]
leptos_meta = { version = "0.7.8", features = ["tracing"] }
leptos = { version = "0.7.8", features = ["csr", "tracing"] }
leptos-use = { version = "0.15.7", features = [] }
utils = { workspace = true }
