[unstable]
codegen-backend = true

# Fast high-level
[profile.dev]
codegen-backend = "cranelift"
opt-level = 1

# Optimize deps
[profile.dev.package."*"]
codegen-backend = "llvm"
opt-level = 3

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
