[alias]
xtask = "run -p xtask --"
x = "xtask"
rs = "run-script"
t = "test-all-features"
# db = "-q r -p ysurreal --"
db = "r -p ymap --bin db --"
se = "rs source-env"
xcb = "xcode-build-rs --colour --manifest-dir . test"