[alias]
r = [
  "run",
  # "-Zcodegen-backend",
  # "--config",
  # "profile.dev.codegen-backend = \"cranelift\"",
]
xdb = ["r", "-p", "xdb", "--"]
xserver = ["r", "-p", "xserver", "--"]
xapp = ["r", "-p", "xapp", "--"]
xdiscord = ["r", "-p", "xdiscord", "--"]
xpueue = ["r", "-p", "xpueue", "--"]
t = ["test-all-features"]


[term]
color = "always"

[build]
# rustflags = ['--cfg=getrandom_backend="wasm_js"']

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]
