[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
time = { version = "0.3.41", features = ["local-offset", "macros"] }
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.19", features = ["fmt", "env-filter", "time"] }
