[watch]
ignore = [
    # The Leptonic build writes these files. Not ignoring them could lead to infinite rebuilds when using `trunk serve`.
    "./public/js",
    # The Leptonic build writes these files. Not ignoring them could lead to infinite rebuilds when using `trunk serve`.
    "./style/leptonic"
]

[serve]
address = "127.0.0.1"
port = 4001
open = false
