[package]
name = "thing"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
surrealdb = "2.2.1"
tracing = "0.1.41"
surrealdb-layers.workspace = true
db.workspace = true
