[package]
name = "env"
version = "0.1.0"
edition = "2024"

[features]
db = []
db-root-creds = []
load-through-env = ["include_toml_key/load-through-env"]

[dependencies]
cfg-if = "1.0.0"
include_toml_key = { workspace = true }
